AMC/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Top.as_view(), name='top'),
    path('event/', include('event.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

event/urls.py
from django.urls import path
from . import views

app_name = 'event'

urlpatterns = [
    path('', views.EventNew.as_view(), name='event_new'),
    path('new/', views.EventNew.as_view(), name='event_new'),
    path('detail/<uuid:pk>/', views.EventDetail.as_view(), name='event_detail'),
    path('detail/<uuid:pk>/result/new/', views.ResultNew.as_view(), name='result_new'),
    path('detail/<uuid:pk>/result/export/', views.result_export, name='result_export'),
    path('detail/<uuid:event_pk>/result/delete/<int:pk>/', views.GameDelete.as_view(), name='game_delete'),
    path('join/<uuid:pk>/new/', views.PlayerNew.as_view(), name='player_new'),
    path('detail/<uuid:event_pk>/player/<int:pk>/', views.PlayerEdit.as_view(), name='player_edit'),
]

event/forms.py
import numpy as np
from django import forms
from .models import Event, Player, Result


class EventForm(forms.ModelForm):
    """イベントフォーム"""

    start_date = forms.DateTimeField(label='開催日時',
                                     widget=forms.DateTimeInput(attrs={'autocomplete': 'off'}))

    class Meta:
        model = Event
        fields = '__all__'
        widget = {
            'start_date': forms.DateTimeInput(attrs={'autocomplete': 'off'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['players'].disabled = True
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_point_at_start(self):
        point_at_start = self.cleaned_data['point_at_start']
        if point_at_start % 1000 != 0:
            raise forms.ValidationError('配給原点は1000点単位で入力してください。')
        return point_at_start


class PlayerForm(forms.ModelForm):

    class Meta:
        model = Player
        fields = ('event', 'name', )
        widgets = {'event': forms.HiddenInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class PlayerEditForm(PlayerForm):

    class Meta(PlayerForm.Meta):
        exclude = ('event', )


class ResultForm(forms.Form):

    p1 = forms.ModelChoiceField(label="参加者", queryset=None)
    p2 = forms.ModelChoiceField(label="参加者", queryset=None)
    p3 = forms.ModelChoiceField(label="参加者", queryset=None)
    p4 = forms.ModelChoiceField(label="参加者", queryset=None)
    point_p1 = forms.IntegerField(max_value=100000, min_value=-100000)
    point_p2 = forms.IntegerField(max_value=100000, min_value=-100000)
    point_p3 = forms.IntegerField(max_value=100000, min_value=-100000)
    point_p4 = forms.IntegerField(max_value=100000, min_value=-100000)
    pt_ex_p1 = forms.IntegerField(max_value=100, min_value=-100)
    pt_ex_p2 = forms.IntegerField(max_value=100, min_value=-100)
    pt_ex_p3 = forms.IntegerField(max_value=100, min_value=-100)
    pt_ex_p4 = forms.IntegerField(max_value=100, min_value=-100)

    event = None

    def __init__(self, queryset=None, *args, **kwargs):
        self.event = kwargs.pop('event')
        super(ResultForm, self).__init__(*args, **kwargs)
        qs = Player.objects.filter(event=self.event)
        self.fields['p1'].queryset = qs
        self.fields['p2'].queryset = qs
        self.fields['p3'].queryset = qs
        self.fields['p4'].queryset = qs

    def clean_point_p1(self):
        point_p1 = self.cleaned_data['point_p1']
        if point_p1 % 100 != 0:
            raise forms.ValidationError('点数は100点単位で入力してください。')
        return point_p1

    def clean_point_p2(self):
        point_p2 = self.cleaned_data['point_p2']
        if point_p2 % 100 != 0:
            raise forms.ValidationError('点数は100点単位で入力してください。')
        return point_p2

    def clean_point_p3(self):
        point_p3 = self.cleaned_data['point_p3']
        if point_p3 % 100 != 0:
            raise forms.ValidationError('点数は100点単位で入力してください。')
        return point_p3

    def clean_point_p4(self):
        point_p4 = self.cleaned_data['point_p4']
        if point_p4 % 100 != 0:
            raise forms.ValidationError('点数は100点単位で入力してください。')
        return point_p4

    def clean(self):
        cleaned_data = super().clean()
        # distinct players check
        if len({cleaned_data[i] for i in ['p1', 'p2', 'p3', 'p4']}) < 4:
            raise forms.ValidationError('Duplicate player')
        # point total check
        diff = sum([cleaned_data[i] for i in ['point_p1', 'point_p2', 'point_p3', 'point_p4']]) - self.event.point_at_start * self.event.players
        if diff != 0:
            raise forms.ValidationError('Sum of points is incorrect.(' + str(diff) + ')')
        # ex-point total check
        diff = sum([cleaned_data[i] for i in ['pt_ex_p1', 'pt_ex_p2', 'pt_ex_p3', 'pt_ex_p4']])
        if diff != 0:
            raise forms.ValidationError('Sum of ex-points is incorrect.(' + str(diff) + ')')
        return cleaned_data

event/views.py
import csv
import pandas as pd
import numpy as np
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import redirect, resolve_url, render
from django.utils import timezone
from django.views import generic
from .models import Event, Player, Game, Result
from .forms import EventForm, PlayerForm, PlayerEditForm, ResultForm
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden


def paginate_queryset(request, queryset, count):
    """Pageオブジェクトを返す。

    ページングしたい場合に利用してください。

    countは、1ページに表示する件数です。
    返却するPgaeオブジェクトは、以下のような感じで使えます。

        {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}">Prev</a>
        {% endif %}

    また、page_obj.object_list で、count件数分の絞り込まれたquerysetが取得できます。

    """
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj


def post_index(request):
    post_list = Result.objects.all()
    page_obj = paginate_queryset(request, post_list, 1)
    context = {
        'post_list': page_obj.object_list,
        'page_obj': page_obj,
    }
    return render(request, 'app/post_list.html', context)


class EventNew(generic.CreateView):
    model = Event
    template_name = 'event/event_new.html'
    form_class = EventForm

    def form_valid(self, form):
        event = form.save(commit=False)
        # default event name
        if event.title is None:
            event.title = str(event.start_date) + "の麻雀大会"
        event.save()
        return redirect('event:event_detail', pk=event.pk)


class EventDetail(generic.DetailView):
    model = Event
    template_name = 'event/event_detail.html'
    result_df = None

    def get_context_data(self, **kwargs):
        context = super(EventDetail, self).get_context_data(**kwargs)
        try:
            player = Player.objects.filter(event=self.kwargs['pk'])
            context['player_list'] = player
        except Player.DoesNotExist:
            context['player_list'] = None
        # Result Summary
        df = pd.DataFrame.from_records(Result.objects.filter(game__event=self.kwargs['pk']).values('pt', 'pt_uma', 'pt_ex', 'game', 'player__name'))
        if not df.empty:
            self.result_df = pd.pivot_table(df, values=["pt", "pt_uma", "pt_ex"], index="game", columns="player__name", aggfunc="sum")  # .reorder_levels([1, 0], axis=1)
            self.result_df = pd.concat([self.result_df.xs('pt', level=0, axis=1).assign(pt_type='normal'),
                                        self.result_df.xs('pt_uma', level=0, axis=1).assign(pt_type='uma'),
                                        self.result_df.xs('pt_ex', level=0, axis=1).assign(pt_type='ex'),
                                        ])
            result_summary = self.result_df.drop('pt_type', axis=1).applymap(lambda x: str(int(x)) if not np.isnan(x) else 'nan').groupby(level=0).agg(lambda x: ', '.join(x))
            # Result Total
            result_total = self.result_df.groupby(by=['pt_type']).sum()
            result_total = result_total.T
            result_total['total'] = result_total['normal'] + result_total['uma'] + result_total['ex']
            result_total = result_total.T
            result_total = result_total.assign(sortkey = lambda x:[1 if i=='normal' else 2 if i=='uma' else 3 if i=='ex' else 4 for i in result_total.index]) \
                                       .sort_values(by=['sortkey']) \
                                       .drop(['sortkey'], axis=1)
            result_total.index = ['素点', 'ウマ', 'その他', '合計']
        else:
            result_summary = pd.DataFrame(index=[], columns=[])
            result_total = pd.DataFrame(index=[], columns=[])
        context['result_summary'] = result_summary
        context['result_total'] = result_total
        return context


class PlayerNew(generic.CreateView):
    model = Player
    template_name = 'event/player_new.html'
    form_class = PlayerForm
    event = None

    def get_initial(self):
        self.event = Event.objects.get(pk=self.kwargs['pk'])
        return {'event': self.event}

    def get_context_data(self, **kwargs):
        context = super(PlayerNew, self).get_context_data(**kwargs)
        context['event'] = self.event
        return context

    def form_valid(self, form):
        player = form.save(commit=False)
        player.save()
        return redirect('event:event_detail', pk=self.kwargs['pk'])


class PlayerEdit(generic.UpdateView):
    model = Player
    template_name = 'event/player_edit.html'
    form_class = PlayerEditForm

    def get_context_data(self, **kwargs):
        context = super(PlayerEdit, self).get_context_data(**kwargs)
        context['event_pk'] = self.kwargs['event_pk']
        return context

    def form_valid(self, form):
        player = form.save(commit=False)
        player.save()
        return redirect('event:event_detail', pk=self.kwargs['event_pk'])


class ResultNew(generic.FormView):
    template_name = 'event/result_new.html'
    form_class = ResultForm
    event = None

    def get_form_kwargs(self):
        kwargs = super(ResultNew, self).get_form_kwargs()
        self.event = Event.objects.get(pk=self.kwargs['pk'])
        kwargs['event'] = self.event
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(ResultNew, self).get_context_data(**kwargs)
        context['event'] = self.event
        return context

    def form_valid(self, form):
        df = pd.DataFrame({'player': [form.cleaned_data['p1'],
                                      form.cleaned_data['p2'],
                                      form.cleaned_data['p3'],
                                      form.cleaned_data['p4']],
                           'point': [form.cleaned_data['point_p1'],
                                     form.cleaned_data['point_p2'],
                                     form.cleaned_data['point_p3'],
                                     form.cleaned_data['point_p4']],
                           'pt_ex': [form.cleaned_data['pt_ex_p1'],
                                     form.cleaned_data['pt_ex_p2'],
                                     form.cleaned_data['pt_ex_p3'],
                                     form.cleaned_data['pt_ex_p4']]
                           })
        # column名indexに入っているのは最初の席順（起家=0）
        df = df.reset_index().sort_values(by=["point", "index"], ascending=[False, True])
        # uma
        uki_n = df.query("point >= 30000").shape[0]
        if self.event.uma_method in ['B1', 'B2', 'B3', 'B4']:
            uma_pattern = uki_n
            if uki_n == 1:
                pt_uma = [6, -1, -2, -3]
            elif uki_n == 2:
                pt_uma = [2, 1, -1, -2]
            elif uki_n == 3:
                pt_uma = [3, 2, 1, -6]
            elif uki_n == 0:
                pt_uma = [0, 0, 0, 0]   # 浮き無の場合はウマ0で登録
            pt_uma = [i * 5 for i in pt_uma]
        else:
            uma_pattern = 0
            if self.event.uma_method == 'A1':
                pt_uma = [10, 5, -5, 10]
            elif self.event.uma_method == 'A2':
                pt_uma = [20, 10, -10, -20]
            elif self.event.uma_method == 'A3':
                pt_uma = [30, 10, -10, -30]

        # game create
        game = Game.objects.create(event=self.event, uma_pattern=uma_pattern)

        # round
        if self.event.rounding_method == 1:     # Truncate
            pt_round_func = (lambda x: np.trunc(x / 1000 - 30))
        elif self.event.rounding_method == 2:     # 4/5
            pt_round_func = (lambda x: np.floor((x + 500) / 1000) - 30)
        elif self.event.rounding_method == 3:     # 5/6
            pt_round_func = (lambda x: np.floor((x + 400) / 1000) - 30)

        df = df.assign(rank=[1, 2, 3, 4], pt=pt_round_func(df["point"]), pt_uma=pt_uma, pt_ex=df["pt_ex"])
        # Top pt recalc
        df = df.reset_index(drop=True)
        df.loc[0, 'pt'] = -sum(df.loc[1:3, 'pt'])
        for index, item in df.iterrows():
            Result.objects.create(game=game,
                                  player=item['player'],
                                  point=item['point'],
                                  rank=item['rank'],
                                  pt=item['pt'],
                                  pt_uma=item['pt_uma'],
                                  pt_ex=item['pt_ex'],
                                  )
        return redirect('event:event_detail', pk=self.kwargs['pk'])


class GameDelete(generic.DeleteView):
    model = Game
    template_name = 'event/game_delete_confirm.html'

    def get_success_url(self):
        return resolve_url('event:event_detail', pk=self.kwargs['event_pk'])


def result_export(request, pk):
    response = HttpResponse(content_type='text/csv', charset='cp932')
    response['Content-Disposition'] = 'attachment; filename="result.csv"'
    # Result Summary
    df = pd.DataFrame.from_records(
        Result.objects.filter(game__event=pk).values('pt', 'pt_uma', 'game', 'player__name'))
    if not df.empty:
        result_df = pd.pivot_table(df, values=["pt", "pt_uma"], index="game", columns="player__name",
                                        aggfunc="sum")  # .reorder_levels([1, 0], axis=1)
        result_df.reset_index(inplace=True, drop=True)
        result_df.index = result_df.index + 1
        result_df = pd.concat([result_df.xs('pt', level=0, axis=1).assign(pt_type='normal'),
                               result_df.xs('pt_uma', level=0, axis=1).assign(pt_type='uma')])
    else:
        result_df = pd.DataFrame(index=[], columns=[])
    # for p in Result.objects.filter(game__event__pk=pk).order_by('game').select_related('player'):
    #     writer.writerow([i, p.player.name, p.participant.first_name, p.participant.email, p.status])

event/templates/event/base.html
{% extends 'base.html' %}

{% block content_parent %}
    <div class="content container">
        <div class="row">
            <div class="col-xs-12">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

event/templates/event/event_detail.html
{% extends 'event/base.html' %}
{% load tags %}

{% block content %}
<div class="event">
    <a class="btn btn-info" href="{% url 'event:player_new' pk=event.pk %}">参加者追加</a>
    <a class="btn btn-info" href="{% url 'event:result_new' pk=event.pk %}">成績を記録</a>
    {% if not result_summary.empty %}
    <a class="btn btn-link" href="{% url 'event:result_export' pk=event.pk %}">成績をダウンロード</a>
    {% endif %}
    <h1>{{ event.title }}</h1>
    <p>参加者にこのURLを共有：{{ request.build_absolute_uri }}</p>
    <h4>ルール</h4>
    <ul>
        <li>配給原点：{{ event.point_at_start }}</li>
        <li>端数処理：{{ event.rounding_method|lookup_rounding_method }}</li>
        <li>ウマ計算：{{ event.uma_method|lookup_uma_method }}</li>
    </ul>
    <hr>
    <h4>参加者</h4>
    {% for player in player_list %}
    <span class="player">
        <a href="{% url 'event:player_edit' event_pk=event.pk pk=player.pk %}">{{ player.name }}</a>
    </span>

    {% endfor %}
    <hr>
    <h4>成績サマリー</h4>
    {% if not result_summary.empty %}
    <table class="table table-striped">
        <thead>
        <td>内訳</td>
        {% for column in result_total.columns %}
        <td>{{ column }}</td>
        {% endfor %}
        </thead>
        <tbody>
        {% for index, row in result_total.iterrows %}
        <tr>
            <th>{{ index }}</th>
            {% for item in row %}
            <td>{{ item|floatformat }}</td>
            {% endfor %}
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <hr>
    <h4>すべての結果(素点, ウマ, その他)</h4>
    <table class="table table-striped">
        <thead>
        {% for column in result_summary.columns %}
        <td>{{ column }}</td>
        {% endfor %}
        <td></td>
        </thead>
        <tbody>
        {% for index, row in result_summary.iterrows %}
        <tr>
            {% for item in row %}
            <td>{% if item != 'nan（nan）' %} {{ item }} {% endif %}</td>
            {% endfor %}
            <th><a href="{% url 'event:game_delete' event_pk=event.pk pk=index %}">
                <i class="fas fa-trash-alt"></i>
            </a></th>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
{% endblock %}

event/templates/event/event_new.html
{% extends 'event/base.html' %}

{% block content %}
<div class="event">
    <h3>イベントの新規作成</h3>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="field">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <div class="helptext">{{ field.help_text }}</div>
                {% endif %}
                {{ field.errors }}
            </div>
        {% endfor %}
        <button type="submit" class="save btn btn-primary">作成</button>
    </form>
</div>
{% endblock %}

event/templates/event/game_delete_confirm.html
{% extends 'event/base.html' %}

{% block content %}
    <h3>結果の削除</h3>
    <form method="POST" class="post-form">{% csrf_token %}
        <button type="submit" class="save btn btn-danger">結果を削除する</button>
    </form>
{% endblock %}

event/templates/event/player_edit.html
{% extends 'event/base.html' %}

{% block content %}
<div class="event">
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="register" class="save btn btn-primary">参加名修正</button>
        <a class="btn btn-secondary" href="{% url 'event:event_detail' pk=event_pk %}">戻る</a>
    </form>
</div>
{% endblock %}

event/templates/event/player_new.html
{% extends 'event/base.html' %}

{% block content %}
<div class="event">
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="register" class="save btn btn-primary">参加登録</button>
        <a class="btn btn-secondary" href="{% url 'event:event_detail' pk=event.pk %}">戻る</a>
    </form>
</div>
{% endblock %}

event/templates/event/result_new.html
{% extends 'event/base.html' %}

{% block content %}
<div class="event">
    <form method="POST" enctype="multipart/form-data" class="post-form">{% csrf_token %}
        {{ form.non_field_errors }}
<!--        {% if form.errors %}-->
<!--        <div class="errorlist">-->
<!--            {% for errors in form.errors.values %}-->
<!--                {% for error in errors %}-->
<!--                    {{ error }}<br>-->
<!--                {% endfor %}-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--        {% endif %}-->
        <table class="table table-striped">
            <thead>
                <td>開始時風</td>
                <td>参加者</td>
                <td>点数</td>
                <td>その他得点(千点単位)</td>
                <td></td>
            </thead>
            <tbody>
                <tr>
                    <th>東家（起家）</th>
                    <td>{{ form.p1 }}</td>
                    <td>{{ form.point_p1 }}</td>
                    <td>{{ form.pt_ex_p1 }}</td>
                    <td>{{ form.point_p1.errors }}</td>
                </tr>
                <tr>
                    <th>南家</th>
                    <td>{{ form.p2 }}</td>
                    <td>{{ form.point_p2 }}</td>
                    <td>{{ form.pt_ex_p2 }}</td>
                    <td>{{ form.point_p2.errors }}</td>
                </tr>
                <tr>
                    <th>西家</th>
                    <td>{{ form.p3 }}</td>
                    <td>{{ form.point_p3 }}</td>
                    <td>{{ form.pt_ex_p3 }}</td>
                    <td>{{ form.point_p3.errors }}</td>
                </tr>
                <tr>
                    <th>北家</th>
                    <td>{{ form.p4 }}</td>
                    <td>{{ form.point_p4 }}</td>
                    <td>{{ form.pt_ex_p4 }}</td>
                    <td>{{ form.point_p4.errors }}</td>
                </tr>
            </tbody>
        </table>
        <button type="submit" class="save btn btn-primary">結果登録</button>
        <a class="btn btn-secondary" href="{% url 'event:event_detail' pk=event.pk %}">戻る</a>
    </form>
</div>
{% endblock %}