AMC/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Top.as_view(), name='top'),
    path('event/', include('event.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

event/urls.py
from django.urls import path
from . import views

app_name = 'event'

urlpatterns = [
    path('', views.EventNew.as_view(), name='event_new'),
    path('new/', views.EventNew.as_view(), name='event_new'),
    path('detail/<uuid:pk>/', views.EventDetail.as_view(), name='event_detail'),
    path('detail/<uuid:pk>/result/new/', views.ResultNew.as_view(), name='result_new'),
    path('detail/<uuid:pk>/result/export/', views.result_export, name='result_export'),
    path('detail/<uuid:event_pk>/result/delete/<int:pk>/', views.GameDelete.as_view(), name='game_delete'),
    path('join/<uuid:pk>/new/', views.PlayerNew.as_view(), name='player_new'),
    path('detail/<uuid:event_pk>/player/<int:pk>/', views.PlayerEdit.as_view(), name='player_edit'),
]

event/forms.py
import numpy as np
from django import forms
from .models import Event, Player, Result


class EventForm(forms.ModelForm):
    """イベントフォーム"""

    start_date = forms.DateTimeField(label='開催日時',
                                     widget=forms.DateTimeInput(attrs={'autocomplete': 'off'}))

    class Meta:
        model = Event
        fields = '__all__'
        widget = {
            'start_date': forms.DateTimeInput(attrs={'autocomplete': 'off'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['players'].disabled = True
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_point_at_start(self):
        point_at_start = self.cleaned_data['point_at_start']
        if point_at_start % 1000 != 0:
            raise forms.ValidationError('配給原点は1000点単位で入力してください。')
        return point_at_start


class PlayerForm(forms.ModelForm):

    class Meta:
        model = Player
        fields = ('event', 'name', )
        widgets = {'event': forms.HiddenInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class PlayerEditForm(PlayerForm):

    class Meta(PlayerForm.Meta):
        exclude = ('event', )


class ResultForm(forms.Form):

    p1 = forms.ModelChoiceField(label="参加者", queryset=None)
    p2 = forms.ModelChoiceField(label="参加者", queryset=None)
    p3 = forms.ModelChoiceField(label="参加者", queryset=None)
    p4 = forms.ModelChoiceField(label="参加者", queryset=None)
    point_p1 = forms.IntegerField(max_value=100000, min_value=-100000)
    point_p2 = forms.IntegerField(max_value=100000, min_value=-100000)
    point_p3 = forms.IntegerField(max_value=100000, min_value=-100000)
    point_p4 = forms.IntegerField(max_value=100000, min_value=-100000)
    pt_ex_p1 = forms.IntegerField(max_value=100, min_value=-100)
    pt_ex_p2 = forms.IntegerField(max_value=100, min_value=-100)
    pt_ex_p3 = forms.IntegerField(max_value=100, min_value=-100)
    pt_ex_p4 = forms.IntegerField(max_value=100, min_value=-100)

    event = None

    def __init__(self, queryset=None, *args, **kwargs):
        self.event = kwargs.pop('event')
        super(ResultForm, self).__init__(*args, **kwargs)
        qs = Player.objects.filter(event=self.event)
        self.fields['p1'].queryset = qs
        self.fields['p2'].queryset = qs
        self.fields['p3'].queryset = qs
        self.fields['p4'].queryset = qs

    def clean_point_p1(self):
        point_p1 = self.cleaned_data['point_p1']
        if point_p1 % 100 != 0:
            raise forms.ValidationError('点数は100点単位で入力してください。')
        return point_p1

    def clean_point_p2(self):
        point_p2 = self.cleaned_data['point_p2']
        if point_p2 % 100 != 0:
            raise forms.ValidationError('点数は100点単位で入力してください。')
        return point_p2

    def clean_point_p3(self):
        point_p3 = self.cleaned_data['point_p3']
        if point_p3 % 100 != 0:
            raise forms.ValidationError('点数は100点単位で入力してください。')
        return point_p3

    def clean_point_p4(self):
        point_p4 = self.cleaned_data['point_p4']
        if point_p4 % 100 != 0:
            raise forms.ValidationError('点数は100点単位で入力してください。')
        return point_p4

    def clean(self):
        cleaned_data = super().clean()
        # distinct players check
        if len({cleaned_data[i] for i in ['p1', 'p2', 'p3', 'p4']}) < 4:
            raise forms.ValidationError('Duplicate player')
        # point total check
        diff = sum([cleaned_data[i] for i in ['point_p1', 'point_p2', 'point_p3', 'point_p4']]) - self.event.point_at_start * self.event.players
        if diff != 0:
            raise forms.ValidationError('Sum of points is incorrect.(' + str(diff) + ')')
        # ex-point total check
        diff = sum([cleaned_data[i] for i in ['pt_ex_p1', 'pt_ex_p2', 'pt_ex_p3', 'pt_ex_p4']])
        if diff != 0:
            raise forms.ValidationError('Sum of ex-points is incorrect.(' + str(diff) + ')')
        return cleaned_data

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'css/event.css' %}">

    <title>麻雀結果記録帳</title>
</head>
<body>
    <!-- ナビバー -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'top' %}">TOP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>

    {% block content_parent %}
    {% endblock %}

    <script>
        $(function () {
            $("#id_start_date").datetimepicker({
                format: 'Y-m-d',
                timepicker: false
            });
        });
<!--      $(function () {-->
<!--          // datepicker-->
<!--          let dateFormat = 'yy-mm-dd';-->
<!--          $('#id_start_at_0').datepicker({-->
<!--              dateFormat: dateFormat-->
<!--          });-->

<!--          // timedropper-->
<!--          $("#id_start_at_1").timeDropper({-->
<!--              format: "H:mm",-->
<!--              setCurrentTime: false,-->
<!--          });-->
<!--      });-->
    </script>

</body>
</html>

templates/top.html
{% extends "base.html" %}
{% block content_parent %}
    <div class="container mt-3">
        <h2>Test Program</h2>
        <a class="btn btn-primary" href="{% url 'event:event_new' %}">イベント新規作成</a>
    </div>
{% endblock %}